### ISSUE TITLE
Explain how to include examples with a project

### ISSUE THREAD

**Issue by trosel** [chivalry/meta-python#1]
explain that Example files / Tutorial files would have to go _outside_ the top most directory of the entire Package. 

If you try to run a script from within your package structure, using a relative import like `..polygons.polygons` you'll get a `System Error: Cannot import ''` etc. http://stackoverflow.com/questions/33837717/systemerror-parent-module-not-loaded-cannot-perform-relative-import

**Comment by chivalry** [comment]
You're right. I thought of the same thing. :) Look at what's currently line 173 of `ch_03_modules.md`. I may have added it after you opened this issue. See if you think that's sufficient. https://github.com/chivalry/meta-python/commit/06469af0bea73017ce75d40e7a482bc59792dbb6

**Comment by chivalry** [comment]
Since I clarified the issue, but haven't gotten feedback on the fix, I'm going to go ahead and close this one out.
